{{ config(tags=["staging", "etl"]) }}

with product_sales_vw as (
SELECT PRODUCTID, TOTAL_AMOUNT AS TOTAL_AMOUNT_SALES,
 A.ITEM_NETAMOUNT,
 A.ITEM_TAXAMOUNT,
 A.ITEM_GROSSAMOUNT,
 A.ITEM_NETAMOUNT,
 A.PRODUCTID,
  B.CURRENCY
FROM DQLABS_QA.STAGING.PRODUCT_SALES
)
select * from product_sales_vw