{{ config(
    schema='STG',
    materialized='view'
) }}

WITH raw AS (
    SELECT *
    FROM {{ source('underwriting', 'UNDERWRITING_RAW') }}
)

SELECT 
"Accountants",
"Actuarial Firm",
"ADDASSURED",
"Assured",
"Assured Addr Type",
"Assured Address",
"Assured Customer Type",
"Assured Domicile Country",
"Assured Fax",
"Assured Phone1",
"Assured Phone2",
"Assured Postcode",
"Auditor",
"Broker Commission",
"Broker Contact Name",
"Broker Group",
"Broker Licence/Number",
"Broker Name",
"Broker No",
"Broker Role",
"Business Provider",
"Claims Adjusters",
"Class Type",
"Client",
"Coinsurer",
"Company Leader",
"Cover Holder",
"Cover Holder Addr Type",
"Cover Holder Address",
"Cover Holder Customer Type",
"Cover Holder Domicile Country",
"Cover Holder Fax",
"Cover Holder Phone1",
"Cover Holder Phone2",
"Cover Holder Postcode",
"Entity",
"Expiry Date",
"Grantee",
"Inception Date",
"Intermediary",
"Investment Banking",
"Joint Principal",
"Journalists",
"Lawyers",
"Limit",
"Limit Basis",
"Limit Currency",
"Lloyds Broker",
"Lloyds Leader",
"Lloyds Syndicate",
"Loss Payee",
"Major Class",
"MGA",
"Minor Class",
"Obligor",
"Original CCY",
"Other",
"Policy Line Status",
"Policy Title",
"Pool",
"Reassured",
"Reassured Addr Type",
"Reassured Address",
"Reassured Customer Type",
"Reassured Domicile Country",
"Reassured Fax",
"Reassured Phone1",
"Reassured Phone2",
"Reassured Postcode",
"Reinsurer",
"Service Providers",
"SignedLine",
"Surveyor",
"Third Party Administrators",
"TMHCC Gross Premium",
"Treasury Management",
"Underwriter",
"Underwriting Reference",
"WrittenLine",
"Xs",
"Xs Basis"
from raw
