name: "DBT Impact Analysis on PR"

on:
  pull_request:
    paths:
      - '**/*.sql'
      - '**/*.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  impact-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code (head)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed DBT files
        id: changes
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.sql
            **/*.yml
          include_removed: true
          include_renamed: true
          separator: ","

      - name: Run PR impact analysis via dbt_mcp API
        id: impact-analysis
        env:
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          URL="https://5198-14-99-74-6.ngrok-free.app/api/v1/dbt/github/pr-impact-analysis"
      
          echo "Calling API via POST: $URL"
      
          PAYLOAD=$(cat <<EOF
          {
            "repo": "$GITHUB_REPO",
            "pr_number": "$PR_NUMBER",
            "github_token": "$GITHUB_TOKEN"
          }
          EOF
          )
      
          echo "Payload:"
          echo "$PAYLOAD"
      
          RESPONSE=$(curl -s -X POST "$URL" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d "$PAYLOAD")
      
          echo "API Response:"
          echo "$RESPONSE"
      
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show Summary in Logs
        run: echo "${{ steps.impact-analysis.outputs.response }}"

      - name: Debug changed files
        run: |
          echo "All files: ${{ steps.changes.outputs.all_files }}"
          echo "Added files: ${{ steps.changes.outputs.added_files }}"
          echo "Modified files: ${{ steps.changes.outputs.modified_files }}"
          echo "Removed files: ${{ steps.changes.outputs.removed_files }}"
          echo "Renamed files: ${{ steps.changes.outputs.renamed_files }}"
          echo "All deleted_files	 files: ${{ steps.changes.outputs.deleted_files }}"
          echo "All deleted_files	 files: ${{ steps.changes.outputs }}"
          echo "Combined changed_files_list: ${{ steps.changes.outputs.all_changed_files }},${{ steps.changes.outputs.removed_files }}"
